### ISSUE TITLE
box file name completion doesn't work

### ISSUE THREAD

**Issue by greaber** [mrolli/packer-bash-completion#1]
I'm using the version of the completion that come in bash_it.  It seems to not do normal file name completion in places where you can give a file name argument to packer.

**Comment by mrolli** [comment]
Can you give me an example, what you like to achieve? After selecting the command (build | inspect|...) the completion seeks for template files (*.json files in cwd) only, as this is what packer expects as argument. Is there a use case where any file is expected to be completed?

**Comment by greaber** [comment]
There is a problem with vagrant completion of the names of images produced by packer.  I guess I was just confused and thinking there was some packer completion issue.
